version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: workbox-core
    versions:
    - "> 5.1.4"
  - dependency-name: workbox-google-analytics
    versions:
    - "> 6.0.0"
  - dependency-name: workbox-streams
    versions:
    - "> 5.1.4"
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.25
    - 14.14.27
    - 14.14.28
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.41
    - 15.0.0
  - dependency-name: "@testing-library/user-event"
    versions:
    - 13.0.1
    - 13.0.10
    - 13.0.15
    - 13.0.16
    - 13.0.3
    - 13.0.7
    - 13.1.1
    - 13.1.2
  - dependency-name: eslint
    versions:
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.17.0
    - 4.18.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.18.0
    - 4.20.0
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
    - 26.0.22
  - dependency-name: eslint-plugin-react
    versions:
    - 7.23.1
  - dependency-name: react-redux
    versions:
    - 7.2.3
  - dependency-name: husky
    versions:
    - 5.2.0
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.2
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: workbox-range-requests
    versions:
    - 6.1.0
    - 6.1.1
  - dependency-name: workbox-precaching
    versions:
    - 6.1.0
    - 6.1.1
  - dependency-name: react-scripts
    versions:
    - 4.0.2
    - 4.0.3
  - dependency-name: workbox-routing
    versions:
    - 6.1.0
    - 6.1.1
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.3
    - 11.2.4
    - 11.2.5
  - dependency-name: web-vitals
    versions:
    - 1.1.0
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.11.9
  - dependency-name: node-notifier
    versions:
    - 8.0.1
