#!/bin/bash

# This script runs after a repository has been generated by this template

set -e

replaceName() {
  # $1 = File Name
  # $2 = Repository Owner
  # $3 = Repository Name

  CURRENT_NAME="Yash Totale"
  CURRENT_OWNER="YashTotale"
  CURRENT_REPO="boilerplate-react-with-redux"

  REPLACE_1="s/$CURRENT_NAME/$2/g"
  REPLACE_2="s/$CURRENT_OWNER/$2/g"
  REPLACE_3="s/$CURRENT_REPO/$3/g"
  REPLACE_4="s/Boilerplate React with Redux/${3//[-]/ }/g"

  if [[ "$OSTYPE" == "darwin"* ]]; then
    sed "-i" "" "-e" "$REPLACE_1" "$1"
    sed "-i" "" "-e" "$REPLACE_2" "$1"
    sed "-i" "" "-e" "$REPLACE_3" "$1"
    sed "-i" "" "-e" "$REPLACE_4" "$1"
  else
    sed "-i" "-e" "$REPLACE_1" "$1"
    sed "-i" "-e" "$REPLACE_2" "$1"
    sed "-i" "-e" "$REPLACE_3" "$1"
    sed "-i" "-e" "$REPLACE_4" "$1"
  fi
}


# $1 = Repository Owner
# $2 = Repository Name

find . -type f -name "*" | grep -v node_modules | grep 'src\|public\|package.json\|package-lock.json\|CONTRIBUTING.md\|CODEOWNERS\|AUTHORS' | grep -v '.ico\|.png' | while read -r line; do
  replaceName $line $1 $2
done
