#!/bin/bash

# This script runs after a repository has been generated by this template

set -e

replacer() {
  # $1 = File Name

  echo $1

  CURRENT_NAME="Yash Totale"
  CURRENT_OWNER="YashTotale"
  CURRENT_REPO="boilerplate-react-with-redux"

  REPLACE_1="s/$CURRENT_NAME/$REPO_OWNER/g"
  REPLACE_2="s/$CURRENT_OWNER/$REPO_OWNER/g"
  REPLACE_3="s/$CURRENT_REPO/$REPO_NAME/g"
  REPLACE_4="s/Boilerplate React with Redux/${REPO_NAME//[-]/ }/g"

  if [[ "$OSTYPE" == "darwin"* ]]; then
    sed "-i" "" "-e" "$REPLACE_1" "$1"
    sed "-i" "" "-e" "$REPLACE_2" "$1"
    sed "-i" "" "-e" "$REPLACE_3" "$1"
    sed "-i" "" "-e" "$REPLACE_4" "$1"
  else
    sed "-i" "-e" "$REPLACE_1" "$1"
    sed "-i" "-e" "$REPLACE_2" "$1"
    sed "-i" "-e" "$REPLACE_3" "$1"
    sed "-i" "-e" "$REPLACE_4" "$1"
  fi
}

find . -type f -name "*" | grep -v node_modules | grep 'src\|public\|package.json\|package-lock.json\|CONTRIBUTING.md\|CODEOWNERS\|AUTHORS\|LICENSE.md\' | grep -v '.ico\|.png' | while read -r line; do
  replacer $line
done

echo "Removing unnecessary files..."
rm -rf scripts .github/workflows/template-cleanup.yml .github/workflows/greetings.yml LICENSE.md
